apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: fileless-execution-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
    - name: "Fileless execution detected"
      enabled: true
      id: "R1005"
      description: "Detecting Fileless Execution"
      expressions:
        message: '''Fileless execution detected: exec call "'' + event.comm + ''" is from a malicious source'''
        uniqueId: "event.comm + '_' + event.exepath + '_' + event.pcomm"
        ruleExpression:
          - eventType: "exec"
            expression: "event.exepath.contains('memfd') || event.exepath.startsWith('/proc/self/fd') || event.exepath.matches('/proc/[0-9]+/fd/[0-9]+')"
      profileDependency: 2
      severity: 8
      supportPolicy: false
      isTriggerAlert: true
      mitreTactic: "TA0005"
      mitreTechnique: "T1055"
      tags:
        - "fileless"
        - "execution"
        - "malicious"
