apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: fileless-execution-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
  - name: "Fileless execution detected"
    enabled: true
    id: "R1005"
    description: "Detecting Fileless Execution"
    expressions:
      message: "'Fileless execution detected: exec call \"' + exec.comm + '\" is from a malicious source'"
      unique_id: "exec.comm + '_' + exec.exe_path + '_' + exec.pcomm"
      rule_expression:
        - event_type: "exec"
          expression: "exec.exe_path.contains('memfd') || exec.exe_path.startsWith('/proc/self/fd') || exec.exe_path.matches('/proc/[0-9]+/fd/[0-9]+')"
    profile_dependency: 2
    severity: 8
    support_policy: false
    tags:
      - "fileless"
      - "execution"
      - "malicious"
