apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: symlink-created-over-sensitive-file-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
  - name: "Symlink Created Over Sensitive File"
    enabled: true
    id: "R1010"
    description: "Detects symlink creation over sensitive files"
    expressions:
      message: "'Symlink created over sensitive file: ' + symlink.old_path + ' -> ' + symlink.new_path"
      unique_id: "symlink.comm + '_' + symlink.old_path"
      rule_expression:
        - event_type: "symlink"
          expression: "(symlink.old_path.startsWith('/etc/shadow') || symlink.old_path.startsWith('/etc/sudoers')) && !ap.was_path_opened(symlink.runtime.container_id, symlink.old_path)"
    profile_dependency: 0
    severity: 5
    support_policy: false
    tags:
      - "anomaly"
      - "symlink"
      - "applicationprofile"
