apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: symlink-created-over-sensitive-file-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
  - name: "Symlink Created Over Sensitive File"
    enabled: true
    id: "R1010"
    description: "Detects symlink creation over sensitive files"
    expressions:
      message: "'Symlink created over sensitive file: ' + event.oldpath + ' -> ' + event.newpath"
      unique_id: "event.comm + '_' + event.oldpath"
      rule_expression:
        - event_type: "symlink"
          expression: "(event.oldpath.startsWith('/etc/shadow') || event.oldpath.startsWith('/etc/sudoers')) && !ap.was_path_opened(event.runtime.containerId, event.oldpath)"
    profile_dependency: 0
    severity: 5
    support_policy: true
    tags:
      - "anomaly"
      - "symlink" 
      - "applicationprofile"