apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: symlink-created-over-sensitive-file-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
    - name: "Soft link created over sensitive file"
      enabled: true
      id: "R1010"
      description: "Detects symlink creation over sensitive files"
      expressions:
        message: "'Symlink created over sensitive file: ' + event.oldPath + ' -> ' + event.newPath"
        uniqueId: "event.comm + '_' + event.oldPath"
        ruleExpression:
          - eventType: "symlink"
            expression: "(event.oldPath.startsWith('/etc/shadow') || event.oldPath.startsWith('/etc/sudoers')) && !ap.was_path_opened(event.containerId, event.oldPath)"
      profileDependency: 1
      severity: 5
      supportPolicy: true
      isTriggerAlert: true
      mitreTactic: "TA0006"
      mitreTechnique: "T1005"
      tags:
        - "anomaly"
        - "symlink"
        - "applicationprofile"
