apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: symlink-created-over-sensitive-file-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
  - name: "Symlink Created Over Sensitive File"
    enabled: true
    id: "R1010"
    description: "Detects symlink creation over sensitive files"
    expressions:
      message: "'Symlink created over sensitive file: ' + data.event.OldPath + ' -> ' + data.event.NewPath"
      unique_id: "data.event.Comm + '_' + data.event.OldPath"
      rule_expression:
        - event_type: "symlink"
          expression: "(data.event.OldPath.startsWith('/etc/shadow') || data.event.OldPath.startsWith('/etc/sudoers')) && !ap.was_path_opened(data.event.Event.CommonData.Runtime.ContainerID, data.event.OldPath)"
    profile_dependency: 0
    severity: 1
    support_policy: true
    tags:
      - "files"
      - "malicious"
      - "symlink" 