apiVersion: kubescape.io/v1
kind: Rule
metadata:
  name: unexpected-file-access-rule
  namespace: kubescape
  labels:
    app: kubescape
    tier: security
spec:
  - name: "Unexpected file access"
    enabled: true
    id: "R0002"
    description: "Detects unexpected file access that is not in the baseline"
    expressions:
      message: "Unexpected file access detected: event.Comm with PID event.Pid"
      unique_id: "event.Comm_event.FullPath"
      rule_expression:
        - event_type: "open"
          expression: "!profile_checks.open_dynamic_path"
    profile_dependency:
      required: 0
    severity: 1
    support_policy: false
    tags:
      - "anomaly"
      - "file"
      - "access" 