apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: unexpected-egress-network-traffic-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
  - name: "Unexpected Egress Network Traffic"
    enabled: true
    id: "R0011"
    description: "Detecting unexpected egress network traffic that is not whitelisted by application profile."
    expressions:
      message: "'Unexpected egress network communication to: ' + data.event.DstEndpoint.Addr + ':' + string(data.event.Port) + ' using ' + data.event.Proto + ' from: ' + data.event.Event.CommonData.K8s.BasicK8sMetadata.ContainerName"
      unique_id: "data.event.DstEndpoint.Addr + '_' + string(data.event.Port) + '_' + data.event.Proto"
      rule_expression:
        - event_type: "network"
          expression: "data.event.PktType == 'OUTGOING' && !net.is_private_ip(data.event.DstEndpoint.Addr) && !nn.was_address_in_egress(data.event.Event.CommonData.Runtime.ContainerID, data.event.DstEndpoint.Addr)"
    profile_dependency: 0
    severity: 5 # Medium
    support_policy: false
    tags:
      - "whitelisted"
      - "network"
      - "anomaly"
      - "networkprofile" 