apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: unexpected-egress-network-traffic-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
  - name: "Unexpected Egress Network Traffic"
    enabled: true
    id: "R0011"
    description: "Detecting unexpected egress network traffic that is not whitelisted by application profile."
    expressions:
      message: "'Unexpected egress network communication to: ' + data.event.dst.addr + ':' + string(data.event.port) + ' using ' + data.event.proto + ' from: ' + data.event.k8s.containerName"
      unique_id: "data.event.dst.addr + '_' + string(data.event.port) + '_' + data.event.proto"
      rule_expression:
        - event_type: "network"
          expression: "data.event.pktType == 'OUTGOING' && !net.is_private_ip(data.event.dst.addr) && !nn.was_address_in_egress(data.event.runtime.containerId, data.event.dst.addr)"
    profile_dependency: 0
    severity: 5 # Medium
    support_policy: false
    tags:
      - "whitelisted"
      - "network"
      - "anomaly"
      - "networkprofile" 