apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: unexpected-process-launched-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
  - name: "Unexpected process launched"
    enabled: true
    id: "R0001"
    description: "Detects unexpected process launches that are not in the baseline"
    expressions:
      message: "'Unexpected process launched: ' + exec.comm + ' with PID ' + string(exec.pid)"
      unique_id: "exec.comm + '_' + exec.exe_path"
      rule_expression:
        - event_type: "exec"
          expression: "!ap.was_executed(exec.runtime.container_id, parse.get_exec_path(exec.args, exec.comm))"
    profile_dependency: 0
    severity: 1
    support_policy: false
    tags:
      - "anomaly"
      - "process"
      - "exec"
      - "applicationprofile"
