apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: unexpected-process-launched-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
    - name: "Unexpected process launched"
      enabled: true
      id: "R0001"
      description: "Detects unexpected process launches that are not in the baseline"
      expressions:
        message: "'Unexpected process launched: ' + event.comm + ' with PID ' + string(event.pid)"
        uniqueId: "event.comm + '_' + event.exepath"
        ruleExpression:
          - eventType: "exec"
            expression: "!ap.was_executed(event.containerId, parse.get_exec_path(event.args, event.comm))"
      profileDependency: 0
      severity: 1
      supportPolicy: false
      isTriggerAlert: true
      mitreTactic: "TA0002"
      mitreTechnique: "T1059"
      tags:
        - "anomaly"
        - "process"
        - "exec"
        - "applicationprofile"
