apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: unexpected-domain-request-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
  - name: "Unexpected domain request"
    enabled: true
    id: "R0005"
    description: "Detecting unexpected domain requests that are not whitelisted by application profile."
    expressions:
      message: "'Unexpected domain communication: ' + dns.dns_name"
      unique_id: "dns.comm + '_' + dns.dns_name"
      rule_expression:
        - event_type: "dns"
          expression: "!dns.dns_name.endsWith('.svc.cluster.local.') && !nn.is_domain_in_egress(dns.runtime.container_id, dns.dns_name)"
    profile_dependency: 0
    severity: 1
    support_policy: false
    tags:
      - "dns"
      - "anomaly"
      - "networkprofile"
