apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: unexpected-sensitive-file-access-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
  - name: "Unexpected Sensitive File Access"
    enabled: true
    id: "R0010"
    description: "Detecting access to sensitive files."
    expressions:
      message: "'Unexpected sensitive file access: ' + open.full_path + ' by process ' + open.comm"
      unique_id: "open.comm + '_' + open.full_path"
      rule_expression:
        - event_type: "open"
          expression: "open.full_path.startsWith('/etc/shadow') && !ap.was_path_opened(open.runtime.container_id, open.full_path)"
    profile_dependency: 1
    severity: 5
    support_policy: false
    tags:
      - "files"
      - "anomaly"
      - "applicationprofile"
