apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: unexpected-sensitive-file-access-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
  - name: "Unexpected Sensitive File Access"
    enabled: true
    id: "R0010"
    description: "Detecting access to sensitive files."
    expressions:
      message: "'Unexpected sensitive file access: ' + event.fullPath + ' by process ' + event.comm"
      unique_id: "event.comm + '_' + event.fullPath"
      rule_expression:
        - event_type: "open"
          expression: "event.fullPath.startsWith('/etc/shadow') && !ap.was_path_opened(event.runtime.containerId, event.fullPath)"
    profile_dependency: 1
    severity: 5
    support_policy: false
    tags:
      - "files"
      - "anomaly"
      - "applicationprofile"