apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: malicious-ptrace-usage-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
    - name: "Unexpected Ptrace Syscall Usage"
      enabled: true
      id: "R1015"
      description: "Detecting use of the ptrace syscall that was not seen in the container's application-profile baseline."
      expressions:
        message: "'Unexpected ptrace syscall usage from: ' + event.comm"
        uniqueId: "event.exepath + '_' + event.comm"
        ruleExpression:
          - eventType: "ptrace"
            expression: "true"
      profileDependency: 2
      severity: 5
      supportPolicy: false
      isTriggerAlert: true
      mitreTactic: "TA0005"
      mitreTechnique: "T1622"
      tags:
        - "context:kubernetes"
        - "context:host"
        - "process"
        - "malicious"
