apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: unexpected-system-call-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
    - name: "Syscalls Anomalies in container"
      enabled: true
      id: "R0003"
      description: "Detects unexpected system calls that are not whitelisted by application profile"
      expressions:
        message: "'Unexpected system call detected: ' + event.syscallName + ' with PID ' + string(event.pid)"
        uniqueId: "event.syscallName"
        ruleExpression:
          - eventType: "syscall"
            expression: "!ap.was_syscall_used(event.containerId, event.syscallName)"
      profileDependency: 0
      severity: 1
      supportPolicy: false
      tags:
        - "anomaly"
        - "syscall"
        - "applicationprofile"
