apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: unexpected-system-call-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
  - name: "Unexpected system call"
    enabled: true
    id: "R0003"
    description: "Detects unexpected system calls that are not whitelisted by application profile"
    expressions:
      message: "'Unexpected system call detected: ' + data.event.SyscallName + ' with PID ' + string(data.event.Pid)"
      unique_id: "data.event.SyscallName"
      rule_expression:
        - event_type: "syscall"
          expression: "!ap.was_syscall_used(data.event.Event.CommonData.Runtime.ContainerID, data.event.SyscallName)"
    profile_dependency: 0
    severity: 1
    support_policy: false
    tags:
      - "anomaly"
      - "syscall"
      - "whitelisted" 