apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: unexpected-system-call-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
  - name: "Syscalls Anomalies in container"
    enabled: true
    id: "R0003"
    description: "Detects unexpected system calls that are not whitelisted by application profile"
    expressions:
      message: "'Unexpected system call detected: ' + event.syscallName + ' with PID ' + string(event.pid)"
      unique_id: "event.syscallName"
      rule_expression:
        - event_type: "syscall"
          expression: "!ap.was_syscall_used(event.containerId, event.syscallName)"
    profile_dependency: 0
    severity: 1
    support_policy: false
    tags:
      - "anomaly"
      - "syscall"
      - "applicationprofile"
