apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: crypto-mining-related-port-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
    - name: "Crypto Mining Related Port Communication"
      enabled: true
      id: "R1009"
      description: "Detecting Crypto Miners by suspicious port usage."
      expressions:
        message: "'Detected crypto mining related port communication on port ' + string(event.dstPort) + ' to ' + event.dstAddr + ' with protocol ' + event.proto"
        uniqueId: "event.comm + '_' + string(event.dstPort)"
        ruleExpression:
          - eventType: "network"
            expression: "event.proto == 'TCP' && event.pktType == 'OUTGOING' && event.dstPort in [3333, 45700] && !nn.was_address_in_egress(event.containerId, event.dstAddr)"
      profileDependency: 1
      severity: 3
      supportPolicy: false
      isTriggerAlert: false
      mitreTactic: "TA0011"
      mitreTechnique: "T1071"
      tags:
        - "network"
        - "crypto"
        - "miners"
        - "malicious"
        - "networkprofile"
