apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: crypto-mining-related-port-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
  - name: "Crypto Mining Related Port Communication"
    enabled: true
    id: "R1009"
    description: "Detecting Crypto Miners by suspicious port usage."
    expressions:
      message: "'Detected crypto mining related port communication on port ' + string(event.port) + ' to ' + event.dst.addr + ' with protocol ' + event.proto"
      unique_id: "event.comm + '_' + string(event.port)"
      rule_expression:
        - event_type: "network"
          expression: "event.proto == 'TCP' && event.pktType == 'OUTGOING' && event.port in [3333, 45700] && !nn.was_address_in_egress(event.runtime.containerId, event.dst.addr)"
    profile_dependency: 1
    severity: 3
    support_policy: false
    tags:
      - "network"
      - "crypto"
      - "miners"
      - "malicious" 
      - "networkprofile"