apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: unshare-syscall-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
  - name: "Unshare System Call usage"
    enabled: true
    id: "R1006"
    description: "Detecting Unshare System Call usage, which can be used to escape container."
    expressions:
      message: "'Unshare system call detected: ' + data.event.syscallName + ' with PID ' + string(data.event.pid)"
      unique_id: "data.event.syscallName"
      rule_expression:
        - event_type: "syscall"
          expression: "data.event.syscallName == 'unshare' && !ap.was_syscall_used(data.event.runtime.containerId, data.event.syscallName)"
    profile_dependency: 2
    severity: 5
    support_policy: false
    tags:
      - "syscall"
      - "escape"
      - "unshare"
      - "anomaly"
      - "applicationprofile"