apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: unshare-syscall-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
    - name: "Process tries to escape container"
      enabled: true
      id: "R1006"
      description: "Detecting Unshare System Call usage, which can be used to escape container."
      expressions:
        message: "'Unshare system call (unshare) was called by process (' + event.comm + ')'"
        uniqueId: "event.comm + '_' + 'unshare'"
        ruleExpression:
          - eventType: "unshare"
            expression: "event.pcomm != 'runc' && !ap.was_syscall_used(event.containerId, 'unshare')"
      profileDependency: 2
      severity: 5
      supportPolicy: false
      isTriggerAlert: true
      mitreTactic: "TA0004"
      mitreTechnique: "T1611"
      tags:
        - "unshare"
        - "escape"
        - "unshare"
        - "anomaly"
        - "applicationprofile"
