apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: unshare-syscall-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
    - name: "Unexpected unshare Syscall in Container"
      enabled: true
      id: "R1006"
      description: "Detecting use of the unshare system call (a namespace-manipulation capability that can be used to escape a container) by a non-runc process, where it was not seen in the container's application-profile baseline."
      expressions:
        message: "'Unshare system call (unshare) was called by process (' + event.comm + ')'"
        uniqueId: "event.comm + '_' + 'unshare'"
        ruleExpression:
          - eventType: "unshare"
            expression: "event.pcomm != 'runc' && !ap.was_syscall_used(event.containerId, 'unshare')"
      profileDependency: 1
      profileDataRequired:
        syscalls:
          - exact: "unshare"
      severity: 5
      supportPolicy: false
      isTriggerAlert: true
      mitreTactic: "TA0004"
      mitreTechnique: "T1611"
      tags:
        - "context:kubernetes"
        - "context:container"
        - "unshare"
        - "escape"
        - "unshare"
        - "anomaly"
        - "applicationprofile"
