apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: kernel-module-load-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
  - name: "Kernel Module Load"
    enabled: true
    id: "R1002"
    description: "Detecting Kernel Module Load."
    expressions:
      message: "'Kernel module load syscall (' + data.event.SyscallName + ') was called'"
      unique_id: "data.event.SyscallName"
      rule_expression:
        - event_type: "syscall"
          expression: >
            data.event.SyscallName == 'init_module' ||
            data.event.SyscallName == 'finit_module'
    profile_dependency: 2
    severity: 8
    support_policy: false
    tags:
      - "syscall"
      - "kernel"
      - "module"
      - "load" 