apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: kernel-module-load-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
  - name: "Process tries to load a kernel module"
    enabled: true
    id: "R1002"
    description: "Detecting Kernel Module Load."
    expressions:
      message: "'Kernel module load syscall (' + event.syscallName + ') was called'"
      unique_id: "event.syscallName"
      rule_expression:
        - event_type: "syscall"
          expression: >
            event.syscallName == 'init_module' ||
            event.syscallName == 'finit_module'
    profile_dependency: 2
    severity: 10
    support_policy: false
    tags:
      - "syscall"
      - "kernel"
      - "module"
      - "load"
