apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: kernel-module-load-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
    - name: "Process tries to load a kernel module"
      enabled: true
      id: "R1002"
      description: "Detecting Kernel Module Load."
      expressions:
        message: "'Kernel module load syscall (init_module) was called'"
        uniqueId: "'init_module'"
        ruleExpression:
          - eventType: "syscall"
            expression: >
              'init_module' in event.syscalls ||
              'finit_module' in event.syscalls
      profileDependency: 2
      severity: 10
      supportPolicy: false
      tags:
        - "syscall"
        - "kernel"
        - "module"
        - "load"
