apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: kernel-module-load-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
    - name: "Process tries to load a kernel module"
      enabled: true
      id: "R1002"
      description: "Detecting Kernel Module Load."
      expressions:
        message: "'Kernel module (' + event.module + ') loading attempt with syscall (' + event.syscallName + ') was called by process (' + event.comm + ')'"
        uniqueId: "event.comm + '_' + event.syscallName + '_' + event.module"
        ruleExpression:
          - eventType: "kmod"
            expression: "event.syscallName == 'init_module' || event.syscallName == 'finit_module'"
      profileDependency: 2
      severity: 10
      supportPolicy: false
      isTriggerAlert: true
      mitreTactic: "TA0005"
      mitreTechnique: "T1547.006"
      tags:
        - "kmod"
        - "kernel"
        - "module"
        - "load"
