apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: unexpected-io-uring-operation-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
  - name: "Unexpected io_uring Operation Detected"
    enabled: true
    id: "R1030"
    description: "Detects io_uring operations that were not recorded during the initial observation period, indicating potential unauthorized activity."
    expressions:
      message: "'Unexpected io_uring operation detected: (opcode=' + string(event.opcode) + ') flags=0x' + (has(event.flags) ? string(event.flags) : '0') + ' in ' + event.comm + '.'"
      unique_id: "string(event.opcode) + '_' + event.comm"
      rule_expression:
        - event_type: "iouring"
          expression: "true"
    profile_dependency: 0
    severity: 5
    support_policy: true
    tags:
      - "syscalls"
      - "io_uring"
      - "applicationprofile" 