apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: ebpf-program-load-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
  - name: "eBPF Program Load"
    enabled: true
    id: "R0009"
    description: "Detecting eBPF program load."
    expressions:
      message: "'bpf system call executed in ' + data.event.Event.CommonData.K8s.BasicK8sMetadata.ContainerName"
      unique_id: "data.event.Comm + '_' + data.event.SyscallName"
      rule_expression:
        - event_type: "syscall"
          expression: "data.event.SyscallName == 'bpf' && !ap.was_syscall_used(data.event.Event.CommonData.Runtime.ContainerID, data.event.SyscallName)"
    profile_dependency: 1
    severity: 5
    support_policy: false
    tags:
      - "syscall"
      - "ebpf" 