apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: ebpf-program-load-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
  - name: "eBPF Program Load"
    enabled: true
    id: "R0009"
    description: "Detecting eBPF program load."
    expressions:
      message: "'bpf system call executed in ' + syscall.k8s.container_name"
      unique_id: "syscall.comm + '_' + syscall.syscall_name"
      rule_expression:
        - event_type: "syscall"
          expression: "syscall.syscall_name == 'bpf' && !ap.was_syscall_used(syscall.runtime.container_id, syscall.syscall_name)"
    profile_dependency: 1
    severity: 5
    support_policy: false
    tags:
      - "syscall"
      - "ebpf"
      - "applicationprofile"
