apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: ebpf-program-load-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
  - name: "eBPF Program Load"
    enabled: true
    id: "R0009"
    description: "Detecting eBPF program load."
    expressions:
      message: "'bpf system call executed in ' + data.event.k8s.containerName"
      unique_id: "data.event.comm + '_' + data.event.syscallName"
      rule_expression:
        - event_type: "syscall"
          expression: "data.event.syscallName == 'bpf' && !ap.was_syscall_used(data.event.runtime.containerId, data.event.syscallName)"
    profile_dependency: 1
    severity: 5
    support_policy: false
    tags:
      - "syscall"
      - "ebpf" 
      - "applicationprofile"