apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: ebpf-program-load-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
  - name: "eBPF Program Load"
    enabled: true
    id: "R0009"
    description: "Detecting eBPF program load."
    expressions:
      message: "'bpf system call executed in ' + event.containerName"
      unique_id: "event.comm + '_bpf'"
      rule_expression:
        - event_type: "syscall"
          expression: "'bpf' in event.syscalls && !ap.was_syscall_used(event.containerId, 'bpf')"
    profile_dependency: 1
    severity: 5
    support_policy: false
    tags:
      - "syscall"
      - "ebpf"
      - "applicationprofile"
