apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: unexpected-file-access-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
  - name: "Unexpected file access"
    enabled: true
    id: "R0002"
    description: "Detects unexpected file access that is not in the baseline"
    expressions:
      message: "'Unexpected file access detected: ' + data.event.Comm + ' with PID ' + string(data.event.Pid) + ' to ' + data.event.FullPath"
      unique_id: "data.event.Comm + '_' + data.event.FullPath"
      rule_expression:
        - event_type: "open"
          expression: "!data.profile_checks.open_dynamic_path"
    profile_dependency: 0
    severity: 1
    support_policy: false
    tags:
      - "anomaly"
      - "file"
      - "access" 