apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: unexpected-file-access-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
  - name: "Unexpected file access"
    enabled: true
    id: "R0002"
    description: "Detects unexpected file access that is not in the baseline"
    expressions:
      message: "'Unexpected file access detected: ' + data.event.comm + ' with PID ' + string(data.event.pid) + ' to ' + data.event.fullPath"
      unique_id: "data.event.comm + '_' + data.event.fullPath"
      rule_expression:
        - event_type: "open"
          expression: >
            !ap.was_path_opened(data.event.runtime.containerId, data.event.fullPath) &&
            !(data.event.fullPath.startsWith('/proc') || 
              data.event.fullPath.startsWith('/run/secrets/kubernetes.io/serviceaccount') || 
              data.event.fullPath.startsWith('/var/run/secrets/kubernetes.io/serviceaccount') || 
              data.event.fullPath.startsWith('/tmp')) &&
            (data.event.fullPath.startsWith('/etc') || 
             data.event.fullPath.startsWith('/var/spool/cron/') || 
             data.event.fullPath.startsWith('/var/log/') || 
             data.event.fullPath.startsWith('/var/run/') || 
             data.event.fullPath.startsWith('/dev/shm/') || 
             data.event.fullPath.startsWith('/run/') || 
             data.event.fullPath.startsWith('/var/www/') || 
             data.event.fullPath.startsWith('/var/lib/docker/') || 
             data.event.fullPath.startsWith('/opt/') || 
             data.event.fullPath.startsWith('/usr/local/') || 
             data.event.fullPath.startsWith('/app/') || 
             data.event.fullPath.startsWith('/.dockerenv') || 
             data.event.fullPath.startsWith('/proc/self/environ') || 
             data.event.fullPath.startsWith('/var/lib/kubelet/') || 
             data.event.fullPath.startsWith('/etc/cni/net.d/') || 
             data.event.fullPath.startsWith('/var/run/secrets/kubernetes.io/') || 
             data.event.fullPath.startsWith('/var/run/secrets/kubernetes.io/serviceaccount/') || 
             data.event.fullPath.startsWith('/run/containerd/') || 
             data.event.fullPath.startsWith('/run/flannel/') || 
             data.event.fullPath.startsWith('/run/calico/'))
    profile_dependency: 0
    severity: 1
    support_policy: false
    tags:
      - "anomaly"
      - "file"
      - "open"
      - "applicationprofile"