apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: unexpected-file-access-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
  - name: "Unexpected file access"
    enabled: true
    id: "R0002"
    description: "Detects unexpected file access that is not in the baseline"
    expressions:
      message: "'Unexpected file access detected: ' + event.comm + ' with PID ' + string(event.pid) + ' to ' + event.fullPath"
      unique_id: "event.comm + '_' + event.fullPath"
      rule_expression:
        - event_type: "open"
          expression: >
            (event.fullPath.startsWith('/etc/') ||
            event.fullPath.startsWith('/var/log/') ||
            event.fullPath.startsWith('/var/run/') ||
            event.fullPath.startsWith('/run/') ||
            event.fullPath.startsWith('/var/spool/cron/') ||
            event.fullPath.startsWith('/var/www/') ||
            event.fullPath.startsWith('/var/lib/') ||
            event.fullPath.startsWith('/opt/') ||
            event.fullPath.startsWith('/usr/local/') ||
            event.fullPath.startsWith('/app/') ||
            event.fullPath == '/.dockerenv' ||
            event.fullPath == '/proc/self/environ')
            &&
            !(event.fullPath.startsWith('/run/secrets/kubernetes.io/serviceaccount') ||
              event.fullPath.startsWith('/var/run/secrets/kubernetes.io/serviceaccount') ||
              event.fullPath.startsWith('/tmp'))
            &&
            !ap.was_path_opened(event.runtime.containerId, event.fullPath)
    profile_dependency: 0
    severity: 1
    support_policy: false
    tags:
      - "anomaly"
      - "file"
      - "open"
      - "applicationprofile"