apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: xmr-crypto-mining-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
    - name: "Crypto miner launched"
      enabled: true
      id: "R1007"
      description: "Detecting XMR Crypto Miners by randomx algorithm usage."
      expressions:
        message: "'XMR Crypto Miner process: (' + event.exepath + ') executed'"
        uniqueId: "event.exepath + '_' + event.comm"
        ruleExpression:
          - eventType: "randomx"
            expression: "true"
      profileDependency: 2
      severity: 10
      supportPolicy: false
      isTriggerAlert: true
      mitreTactic: "TA0040"
      mitreTechnique: "T1496"
      tags:
        - "crypto"
        - "miners"
        - "malicious"
