apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: exec-binary-not-in-base-image-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
  - name: "Drifted process executed"
    enabled: true
    id: "R1001"
    description: "Detecting exec calls of binaries that are not included in the base image"
    expressions:
      message: "'Process (' + exec.comm + ') was executed and is not part of the image'"
      unique_id: "exec.comm + '_' + exec.exe_path + '_' + exec.pcomm"
      rule_expression:
        - event_type: "exec"
          expression: >
            (exec.upper_layer == true ||
             exec.pupper_layer == true) &&
            !ap.was_executed(exec.runtime.container_id, parse.get_exec_path(exec.args, exec.comm))
    profile_dependency: 1
    severity: 8
    support_policy: false
    tags:
      - "exec"
      - "malicious"
      - "binary"
      - "base image"
      - "applicationprofile"
