apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: exec-binary-not-in-base-image-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
  - name: "Drifted process executed"
    enabled: true
    id: "R1001"
    description: "Detecting exec calls of binaries that are not included in the base image"
    expressions:
      message: "'Process (' + event.comm + ') was executed and is not part of the image'"
      unique_id: "event.comm + '_' + event.exepath + '_' + event.pcomm"
      rule_expression:
        - event_type: "exec"
          expression: >
            (event.upperlayer == true ||
             event.pupperlayer == true) &&
            !ap.was_executed(event.containerId, parse.get_exec_path(event.args, event.comm))
    profile_dependency: 1
    severity: 8
    support_policy: false
    tags:
      - "exec"
      - "malicious"
      - "binary"
      - "base image"
      - "applicationprofile"
