apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: exec-binary-not-in-base-image-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
  - name: "Exec Binary Not In Base Image"
    enabled: true
    id: "R1001"
    description: "Detecting exec calls of binaries that are not included in the base image"
    expressions:
      message: "'Process (' + data.event.comm + ') was executed and is not part of the image'"
      unique_id: "data.event.comm + '_' + data.event.exepath + '_' + data.event.pcomm"
      rule_expression:
        - event_type: "exec"
          expression: >
            (data.event.upperlayer == true ||
             data.event.pupperlayer == true) &&
            !ap.was_executed(data.event.runtime.containerId, parse.get_exec_path(data.event.args, data.event.comm))
    profile_dependency: 1
    severity: 8
    support_policy: false
    tags:
      - "exec"
      - "malicious"
      - "binary"
      - "base image"
      - "applicationprofile" 