apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: unexpected-capability-used-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
  - name: "Unexpected capability used"
    enabled: true
    id: "R0004"
    description: "Detects unexpected capabilities that are not whitelisted by application profile"
    expressions:
      message: "'Unexpected capability used: ' + data.event.CapName + ' in syscall ' + data.event.Syscall + ' with PID ' + string(data.event.Pid)"
      unique_id: "data.event.Comm + '_' + data.event.CapName"
      rule_expression:
        - event_type: "capabilities"
          expression: "!ap.was_capability_used(data.event.Event.CommonData.Runtime.ContainerID, data.event.CapName)"
    profile_dependency: 0
    severity: 1
    support_policy: false
    tags:
      - "anomaly"
      - "capabilities"
      - "applicationprofile"
