apiVersion: kubescape.io/v1
kind: Rules
metadata:
  name: hardlink-created-over-sensitive-file-rule
  namespace: kubescape
  labels:
    app: kubescape
spec:
  rules:
  - name: "Hard link created over sensitive file"
    enabled: true
    id: "R1012"
    description: "Detecting hardlink creation over sensitive files."
    expressions:
      message: "'Hardlink created over sensitive file: ' + hardlink.old_path + ' - ' + hardlink.new_path"
      unique_id: "hardlink.comm + '_' + hardlink.old_path"
      rule_expression:
        - event_type: "hardlink"
          expression: "(hardlink.old_path.startsWith('/etc/shadow') || hardlink.old_path.startsWith('/etc/sudoers')) && !ap.was_path_opened(hardlink.runtime.container_id, hardlink.old_path)"
    profile_dependency: 1
    severity: 5
    support_policy: true
    tags:
      - "files"
      - "malicious"
      - "applicationprofile"
